### ISSUE TITLE
Error calculating padding for DOM Element

### ISSUE THREAD

**Issue by jonesmac** [XYOracleNetwork/sdk-xyo-react-js#367]
See - https://github.com/XYOracleNetwork/app-explore.xyo.network-react/issues/78

Very unclear why this is happening and only on mobile safari. getPropertyValue should always return a string and therefore replaceAll should never be undefined - https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue

Mostly likely solution is to conditionally call replaceAll with `?` after `getComputedProperty` [here](https://github.com/XYOracleNetwork/sdk-xyo-react-js/blob/main/src/components/TableCell/getRemainingRowWidth.ts)

**Comment by jonesmac** [comment]
closed in #374 

thanks @coder-abdo for your help

**Comment by coder-abdo** [comment]
I am happy to contribute in this awesome project and be a part of this project, thanks to you too for letting me there
