### ISSUE TITLE
NFT Collection Rating Live/Perma Share

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/sdk-xyo-react-js#667]
This should be moved to the Foreventory Project: https://github.com/orgs/xylabs/projects/1/views/1

**Comment by arietrouw** [comment]
https://github.com/xylabs/app-foreventory.com-react/issues/155

**Comment by arietrouw** [comment]
- [ ] Top Collections
- [ ] Collection
- [ ] Wallet
- [ ] Individual NFT

**Comment by jonesmac** [comment]
- [ ] support payload hash for score in route param
- [ ] use payload in route OR use default for TopCollectionsPerEnv
- [ ] share button that builds link with payload hash
- [ ] add schema to route diviner and navigate accordingly

**Comment by jonesmac** [comment]
All done except for individual nft pages.  Captured in #2988
